apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shorty-db-pvc
spec:
  # Docker Desktop provides a default 'hostpath' storage class
  storageClassName: hostpath
  accessModes:
    # ReadWriteOnce means the volume can be mounted as read-write by a single Node.
    # This is suitable for our single-instance SQLite database.
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Request 1 Gibibyte of storage